### ISSUE TITLE
CLA Enter Email Address placeholder

### ISSUE THREAD

**Issue by carlhannes** [qlik-oss/open-source#1]
In `cla-v1.0.md` there is a placeholder for the Email address, looking like this: `THEN SCAN AND SEND TO QLIK USING THE EMAIL ADDRESS [ENTER EMAIL ADDRESS].`

I guess this placeholder should be replaced with "sign-cla@qlik.com"?

Since this file's hash is represented in `sign-cla.md`, it would probably need updating with the correct hash aswell.

**Comment by stefanwalther** [comment]
Thx for reading carefully, thx I am on it (see PR #3 )
